/**
 * @file common.hh
 * @author  Jérôme Borme <jerome.borme@inl.int>
 * @version 1.0
 * @brief Really general definitions
 * @date 2014-04-04 Jérôme Borme: Initial version
 * @copyright
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file defines the types used in the C++ classes, as function
 * of the build target. Note that any change to the types
 * long_unsigned_int and selection_t have to be propagated to the
 * corresponding typedef declarations in dpps.i
 */

#ifndef DPPS_COMMON
#define DPPS_COMMON

// configure.h is generated by CMake from configure.h.in
// It contains VECTOR_SIZE_LONG_LONG

#include "configure.h"

// With x64_64_g++, vector seems to always be indexed on 8 bytes.
//
// On gcc/linux, vector::size returns a size_t of long unsigned int,
// which with data model LP64 (I32LP64) means that long is 64 bits or 8 byte.
// On gcc/mingw32 (for 64 bits), vector::size returns a size_t of long long
// unsigned int, which in the LLP64 (IL32P64) model is 8 byte.
//
// Most int variable we have are used to index vectors, so we call them
// long_unisgned_int and replace this by the appropriate type that happens
// to be 8 byte (because gcc indexes vectors on 8 byte in all cases).
#ifdef VECTOR_SIZE_LONG_LONG
// for mingw64
#define long_unsigned_int long long unsigned int
#else
// all other 64 bit OSes on planet Earth.
// https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models
#define long_unsigned_int long unsigned int
#endif

// for platforms which do not have the POSIX definition.
#ifndef M_PI
#define M_PI 3.14159535897
#endif

// The type holding the selection. The number of bits will define it has
// will define the number of selection that can be used.
#define selection_t int8_t

// mingw32 does not implement std::to_string, std::stod, std::stol
// among others. https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52015
#ifdef _GLIBCXX_HAVE_BROKEN_VSWPRINTF
#include <string>
#include <cstdlib>
namespace std {
std::string to_string (long_unsigned_int x) ;
std::string to_string (long signed int x) ;
std::string to_string (double x) ;
std::string to_string (bool x) ;
inline long_unsigned_int min(long_unsigned_int a, long_unsigned_int b) {return a<b?a:b ;}
}
#define stod(STRING,PTR) strtod(STRING,PTR)
#define stol(STRING,PTR,BASE) strtol(STRING,PTR,BASE)
#endif

#endif
